config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :garden_beds do
    resources :plants, only: [:index, :show]
  end
  resources :plants, only: [:index, :show] do
    resources :garden_beds, only: [:new, :create]
  end
  resources :plantings, only: [:create, :update, :destroy]
  
  root to: 'sessions#home'

  get "/auth/google_oauth2/callback", to: 'sessions#g_log_in'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :garden_beds
    has_many :plantings, through: :garden_beds
    has_many :plants, through: :plantings
    
    has_many :favorite_plants
    has_many :fav_plants, through: :favorite_plants, source: :plant

    validates_presence_of :name, :email
    validates :email, uniqueness: true

    has_secure_password

    def garden_beds_without_plant(plant)
        beds = []
        self.garden_beds.each do |bed|
            if !bed.plants.include?(plant)
                beds << bed
            end
        end
        beds
    end

    def garden_beds_with_plant(plant)
        beds = []
        self.garden_beds.each do |bed|
            if bed.plants.include?(plant)
                beds << bed
            end
        end
        beds
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show, :edit]

    def show
        current_user
        @fav_plants = @user.fav_plants
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            # byebug
            render new_user_path
        end
    end

    def edit
        if current_user.id != params[:id].to_i
            redirect_to edit_user_path(@user)
        end
    end
    
    def update
        if current_user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
    
    def destroy
        current_user.destroy
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :zipcode)
    end
end

app/views/users/_form.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

<%= form_with(model: user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :zipcode %>
    <%= f.number_field :zipcode %>
    <br>
    <% if user.uid.blank? %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
!!admin only

app/views/users/new.html.erb
<h1>Create a Log In</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>
<%= link_to "Edit Profile", edit_user_path(@user) %><br>
<br>
<%= link_to "Logout", {:controller=> "sessions", :action=> "destroy"}, :method => :delete%><br>
<br>
<%= link_to "Create a New Garden Bed", new_garden_bed_path %><br>
<%= link_to "Your Garden Beds", garden_beds_path %><br>
<h3>Your Planted Plants<h3>
<% if @user.plants.any? %>
<ul>
    <% @user.plants.uniq.each do |plant| %>
        <li><%= link_to plant.name, plant_path(plant) %> - <%= plant.spread %> in</li>
    <% end %>
</ul>
<% end %>
<br>
<h3>Your Loved Plants</h3>
<% if @fav_plants.any? %>
<ul>
    <% @fav_plants.each do |plant| %>
        <li><%= link_to plant.name, plant_path(plant) %> - <%= plant.spread %> in - DELETE FAV</li>
    <% end %>
</ul>
<% else %>
    <%= link_to "Find Some Favorites", plants_path %>
<% end %>

<br>
<br>
<br>
<iframe src="https://www.plantmaps.com/hardiness-zone-zipcode.php" name="Find the USDA Hardiness Zone for your Zipocde and Map it" width="210" scrolling="No" frameborder="0" marginheight="0" marginwidth="0">[Your browser doesn't support IFrames. <a href="//www.plantmaps.com/hardiness-zone-zipcode.php" target="_blank">Click here</a> to find the USDA hardiness zone for your zipcode.]</iframe>