config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :garden_beds do
    resources :plants, only: [:index, :show]
  end
  resources :plants, only: [:index, :show] do
    resources :garden_beds, only: [:new, :create]
  end
  resources :plantings, only: [:create, :update, :destroy]
  
  root to: 'sessions#home'

  get "/auth/google_oauth2/callback", to: 'sessions#g_log_in'
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_many :plantings
    has_many :garden_beds, through: :plantings
    has_many :favorite_plants
    has_many :fav_users, through: :favorite_plants, source: :user

    has_many :plant_pairs, foreign_key: :plant_a_id, class_name: "PlantPair", dependent: :delete_all, inverse_of: :plant_a
    has_many :pairs, through: :plant_pairs, source: :plant_b, class_name: 'Plant'

    def self.name_like(search)
        where('lower(name) LIKE ?', "%#{search.downcase}%")
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :set_user
    
    def index
        # byebug
        if params[:search]
            @plants = Plant.name_like(params[:search])
        else
            @plants = Plant.all
        end
        if !!params[:garden_bed_id]
            bed = GardenBed.find_by(id: params[:garden_bed_id])
            @plants = @plants - bed.plants
        end
        # include plant sorting
        # if logged_in? && !!params[:garden_bed_id]
        #     @planted_plants = current_user.plants
        #     @plants_in_bed = garden_bed.plants
        #     @fav_plants = user.fav_plants
        # elsif logged_in?
        #     @planted_plants = current_user.plants
        #     @fav_plants = user.fav_plants
        # end
    end
    
    def show
        @plant = Plant.find(params[:id])
        @planting = Planting.new
        @companions = []
        @antagonists = []
        if @plant.pairs.any?
            @plant.pairs.each do |pair|
                if @plant.plant_pairs.where(:plant_b_id => pair.id)[0][:friend]
                    @companions << pair
                else
                    @antagonists << pair
                end
            end
        end
        if logged_in?
            if @user.plants.include?(@plant)
                @garden_beds_without_plant = @user.garden_beds_without_plant(@plant)
                @garden_beds_with_plant = @user.garden_beds_with_plant(@plant)
                @plantings = []
                @garden_beds_with_plant.each do |bed|
                    @plantings << Planting.find_by(garden_bed_id: bed.id, plant_id: @plant.id)
                end
            else
                @garden_beds_without_plant = @user.garden_beds
            end
        end
        # byebug
        # if logged_in? && !!params[:bed_id]
        #     @planted_plants = current_user.plants
        #     @plants_in_bed = garden_bed.plants
        # elsif logged_in?
        #     @planted_plants = current_user.plants
        # end
    end

    private

    def set_user
        if logged_in?
            current_user
        end
    end

    def search_params
        params.require(:plant).permit(:search)
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/index.html.erb
<h1>Browse Plants</h1>
<div id="search">
<%= form_tag plants_path, method: :get do %>
    Search Plants: <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil%>
<% end %>
<%= link_to "Clear Search", plants_path %>
</div>
<br>

<ul>
<% @plants.each do |plant| %>
    <li><%= link_to plant.name, plant_path(plant) %></li><%# conditional formatting to be added %>
<% end %>
</ul>

<a href=<%= plants_path %>><button>Click me!</button></a>

app/views/plants/show.html.erb
<h1><%= @plant.name %></h1>
<h2><%= @plant.scientific_name %></h2>
<br>
<p>Spacing: <%= @plant.spread %>in.</p>
<br>
<% if @companions.any? %>
    <h3>Companion Plants</h3>
    <% @companions.each do |pair| %>
        <%= link_to pair.name, plant_path(pair) %>
    <% end %>
<% end %>
<% if @antagonists.any? %>
    <h3>Antagonist Plants</h3>
    <% @antagonists.each do |pair| %>
        <%= link_to pair.name, plant_path(pair) %>
    <% end %>
<% end %>
<br>
<br>
<% if !!session[:user_id] %>
    <% if @user.plants.include?(@plant) %>
        <h3>Currently Planted</h3>
            <% x = @garden_beds_with_plant.length - 1 %>
            <% while x >= 0 %>
                <%= link_to @garden_beds_with_plant[x].name, garden_bed_path(@garden_beds_with_plant[x]) %>
                <%= form_with model: @plantings[x] do |f| %>
                    <%= f.hidden_field :id %>
                    <%= f.hidden_field :plant_id %>
                    <%= f.hidden_field :garden_bed_id%>
                    <%= f.label :plant_count, "No. of Plants" %>
                    <%= f.number_field :plant_count, min: 1, step: 1 %>
                    <%= f.submit "Update Plants in Bed" %>
                <% end %>
                    <%= form_with model: @plantings[x], method: "delete" do |f| %><%= f.hidden_field :id %><%= f.hidden_field :garden_bed_id %><%= f.submit "Delete Planting" %><% end %>
                <% x = x-1 %>
            <% end %>
    <% end %>
    <% if @garden_beds_without_plant.length != 0 %>
        <h3>Add Plants to Your Garden</h3>
            <%= form_with model: @planting do |f| %>
            <%= f.hidden_field :plant_id, value: @plant.id %>
                <%= f.label :garden_bed_id, "Select Your Garden Bed"%>
                <%= f.collection_select :garden_bed_id, @garden_beds_without_plant, :id, :name %>
                <br>
                <%= f.label :plant_count, "No. of Plants" %>
                <%= f.number_field :plant_count, min: 1, step: 1 %>
                <br>
                <%= f.submit "Add Plants to Bed" %>
            <% end %>
    <% else %>
        <h2>All of your gardens already have this planted</h2>
    <% end %>
        <br>
    <%= link_to "Create a New Garden Bed for this Plant", new_plant_garden_bed_path(@plant) %>
        <br>
<% end %>