config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :garden_beds do
    resources :plants, only: [:index, :show]
  end
  resources :plants, only: [:index, :show] do
    resources :garden_beds, only: [:new, :create]
  end
  resources :plantings, only: [:create, :update, :destroy]
  
  root to: 'sessions#home'

  get "/auth/google_oauth2/callback", to: 'sessions#g_log_in'
end

app/models/garden_bed.rb
class GardenBed < ApplicationRecord
    belongs_to :user
    has_many :plantings
    has_many :plants, through: :plantings

    validates_presence_of :name, :area
    validates :area, numericality: { greater_than: 0 }
end

app/controllers/garden_beds_controller.rb
class GardenBedsController < ApplicationController
    before_action :require_login
    
    def index
        @garden_beds = User.find(session[:user_id]).garden_beds
    end

    def show
        @garden_bed = GardenBed.find(params[:id])
        @plants_in_bed = @garden_bed.plants
        @plantings = []
        @companions = []
        @antagonists = []
        @garden_area_remaining = @garden_bed.area
        @plants_in_bed.each do |plant|
            planting = Planting.find_by(plant_id: plant.id, garden_bed_id: @garden_bed.id)
            @garden_area_remaining = @garden_area_remaining - calculate_area_of_plant(plant.spread, planting.plant_count)
            @plantings << planting
            if plant.pairs.any?
                plant.pairs.each do |pair|
                    if plant.plant_pairs.where(:plant_b_id => pair.id)[0][:friend]
                        @companions << pair
                    else
                        @antagonists << pair
                    end
                end
            end
        end
        # byebug
    end
    
    def new
        @garden_bed = GardenBed.new
        if params[:plant_id]
            @plant = Plant.find_by(id: params[:plant_id])
        end
    end
    
    def create
        # byebug
        # params.require(:garden_bed).permit(:area_opt, :area, :area_w, :area_l, :area_d)
        if params[:garden_bed][:area_opt] == "Rectangular" # and not empty
            params[:garden_bed][:area] = (params[:garden_bed][:area_w].to_f * params[:garden_bed][:area_l].to_f)
        elsif params[:garden_bed][:area_opt] == "Circular"
            params[:garden_bed][:area] = ((params[:garden_bed][:area_d].to_f / 2)*3.1415)**2
        end
        @garden_bed = GardenBed.new(bed_params)
        if @garden_bed.save
            redirect_to garden_bed_path(@garden_bed)
        else
            render new_garden_bed_path
        end
    end
    
    def edit
        @garden_bed = GardenBed.find(params[:id])
    end
    
    def update
        @garden_bed = GardenBed.find(params[:id])
        if @garden_bed.update(bed_params)
            redirect_to garden_beds_path
        else
            render :edit
        end
    end
    
    def destroy
        GardenBed.find(params[:garden_bed][:id]).destroy
        redirect_to garden_beds_path
    end

    private

    def bed_params
        params.require(:garden_bed).permit(:user_id, :name, :area, :plant_ids)
    end

    def garden_bed
        @garden_bed = Garden_bed.find(params[:id])
    end
    
    def bed_of_user?
        @user.garden_beds.include?(@garden_bed)
    end

    def calculate_area_of_plant(plant_spread, plant_count)
        ((plant_spread**2)/144)*plant_count #change plant_spread and plant_count to a float to ensure the carrots with 2in show up as taking up space in garden
    end
    
end

app/helpers/garden_beds_helper.rb
module GardenBedsHelper
    
end

app/views/garden_beds/edit.html.erb
<h1>Edit Garden Bed - <%= @garden_bed.name %></h1>

<% if @garden_bed.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@garden_bed.errors.count, "error") %> prohibited this garden bed from being saved:</h2>

    <ul>
    <% @garden_bed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

<%= form_with(model: @garden_bed, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :area %>
    <%= f.number_field :area, min: 0.1, step: 0.05 %>
    <br>
    <%= f.submit %>
<% end %>

app/views/garden_beds/index.html.erb
<h1>Your Garden Beds</h1>

<% @garden_beds.each do |bed| %>
    <%= link_to bed.name, garden_bed_path(bed) %> - <%= bed.area%> sq ft   <%= form_with model: bed, method: "delete" do |f| %><%= f.hidden_field :id %><%= f.submit "Delete" %><% end %> <br>
<% end %>
<br>
<%= link_to "Create a New Garden Bed", new_garden_bed_path %><br>

app/views/garden_beds/new.html.erb
<h1>Create a New Garden Bed</h1>
<br>
<% if @garden_bed.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@garden_bed.errors.count, "error") %> prohibited this garden bed from being saved:</h2>

    <ul>
    <% @garden_bed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

<%= form_with(model: @garden_bed, local: true) do |f| %>
<%= f.hidden_field :user_id, :value => session[:user_id] %>
    <% if params[:plant_id] %>
        <%= f.hidden_field :plant_ids, value: @plant.id %>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :area %>
    <br>
    <%= f.radio_button :area_opt, "Regular", checked: "checked", #add clear event for other fields
    onClick: "document.getElementById('garden_bed_area').disabled = false;
    document.getElementById('garden_bed_area_w').disabled = true;
    document.getElementById('garden_bed_area_l').disabled = true;
    document.getElementById('garden_bed_area_d').disabled = true;"%>
    Area of Garden Bed (sq ft):
    <%= f.number_field :area, min: 0.1, step: 0.05, :disabled => false %>
    <br>
    <%= f.radio_button :area_opt, "Rectangular",
    onClick: "document.getElementById('garden_bed_area').disabled = true;
    document.getElementById('garden_bed_area_w').disabled = false;
    document.getElementById('garden_bed_area_l').disabled = false;
    document.getElementById('garden_bed_area_d').disabled = true;"%>
    Dimensions of Rectangular Garden Bed:
    <%= f.label :area_w, "Width(ft)" %><%= f.number_field :area_w, min: 0.1, step: 0.1, :disabled => true %>
    <%= f.label :area_l, "Length(ft)" %><%= f.number_field :area_l, min: 0.1, step: 0.1, :disabled => true %>
    <br>
    <%= f.radio_button :area_opt, "Circular",
    onClick: "document.getElementById('garden_bed_area').disabled = true;
    document.getElementById('garden_bed_area_w').disabled = true;
    document.getElementById('garden_bed_area_l').disabled = true;
    document.getElementById('garden_bed_area_d').disabled = false;"%>
    Dimension of Circular Garden Bed:
    <%= f.label :area_w, "Diameter(ft)" %><%= f.number_field :area_d, min: 0.1, step: 0.1, :disabled => true %>
    <br>
    <%= f.submit %>
<% end %>

app/views/garden_beds/show.html.erb
<h1>Garden Bed - <%= @garden_bed.name %></h1>
<%= link_to "Edit Garden Bed", edit_garden_bed_path(@garden_bed)%>
<p>Garden area(sq ft): <%= @garden_bed.area %></p>
<p>Remaining garden area(sq ft): <%= @garden_area_remaining %> </p>
<br>
<h3>Plants in Bed</h3>
<ul>
<% x = @plants_in_bed.length - 1 %>
<% while x >= 0 %>
    <li><%= link_to @plants_in_bed[x].name, plant_path(@plants_in_bed[x]) %>
    <%= form_with model: @plantings[x], method: "patch" do |f| %>
        <%= f.hidden_field :id %>
        <%= f.hidden_field :plant_id %>
        <%= f.hidden_field :garden_bed_id %>
        <%= f.label :plant_count, "# Planted " %>
        <%= f.number_field :plant_count, min: 1, step: 1 %>
        <%= f.submit "Update Plants in Bed" %>
    <% end %>
    <%= form_with model: @plantings[x], method: "delete" do |f| %><%= f.hidden_field :id %><%= f.hidden_field :garden_bed_id %><%= f.submit "Delete" %><% end %></li>
    <br>
    <% x = x-1 %>
<% end %>
</ul>

<h3>Companion Plants not in Garden Bed</h3>
<% if @companions.any? %>
    <% @companions.each do |pair| %>
        <% if !@plants_in_bed.include?(pair) %>
            <%= link_to pair.name, plant_path(pair) %> - Spacing: <%= pair.spread %> in. - Pairs with ____ currently in garden <br>
            <%= form_with model: Planting.new do |f| %>
                <%= f.hidden_field :garden_bed_id, value: @garden_bed.id %>
                <%= f.hidden_field :plant_id, value: pair.id %>
                <%= f.label :plant_count, "Number to Plant " %>
                <%= f.number_field :plant_count, min: 1, step: 1 %>
                <%= f.submit "Add to Bed" %>
            <% end %>
            <br>
            <br>
        <% end %>
    <% end %>
<% end %>
<br>
<br>
<%= link_to "Find New Plants for this Bed", garden_bed_plants_path(@garden_bed) %>