config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :garden_beds do
    resources :plants, only: [:index, :show]
  end
  resources :plants, only: [:index, :show] do
    resources :garden_beds, only: [:new, :create]
  end
  resources :plantings, only: [:create, :update, :destroy]
  
  root to: 'sessions#home'

  get "/auth/google_oauth2/callback", to: 'sessions#g_log_in'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantTender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> <%# if !!session[:user_id] show one header bar, otherwise show another, except for root(this through template)%>
    <% if !!session[:user_id] %>
      <div id="header">
        <a href= <%= user_path(@user) %>><button>Home</button></a>
        <a href= <%= plants_path%>><button>Plants</button></a>
        <a href= <%= garden_beds_path %>><button>Garden Beds</button></a>
        <a href= <%= edit_user_path(@user) %>><button>Edit Profile</button></a>
      </div>
    <% else %>
      <div id="header">
        <a href= <%= plants_path%>><button>Plants</button></a>
        <a href= <%= root_path %>><button>Home</button></a>
        <a href= <%= new_session_path %>><button>Login</button></a>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>